# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'MyRecipe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MyRecipe
  pod 'Typhoon', '~> 4.0'
  pod 'OCMockito', '~> 5.0'

  target 'MyRecipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
